name: studybuddy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1
  firebase_ui_auth: ^1.9.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  http: ^1.1.0
  image_picker: ^1.0.4
  syncfusion_flutter_calendar: ^23.1.43
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.1
  timezone: ^0.9.2
  permission_handler: ^11.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
